### ISSUE TITLE
vellum-monster uses calculated CR even when CR is passed

### ISSUE THREAD

**Issue by rjclaasen** [grislyeye/vellum-monster#50]
Given the following HTML:
```
<vellum-monster
  hp="200"
  ac="18"
  cr="2"
  xp="450"
></vellum-monster>
```

Expected behavior:
It will display the following text in the stat block:
> **Armor Class** 18
> **Hit Points** 200
> **Challenge** 2 (450 XP)

Actual behavior:
It will display the following text in the stat block:

> **Armor Class** 18
> **Hit Points** 200
> **Challenge** 4 (450 XP)

Thank you a lot for all of the time and work you put into this project!

**Comment by rg-wood** [comment]
Thanks for using this project and submitting bugs. Hope you find it useful!

This is closed by:

302a2b08fa76dad35c7b9f54e3cd5f6c970102a5

Fixed in version `v0.16.5`.

**Comment by rg-wood** [comment]
@rjclaasen Does that mean the CR calculations were also off? I've made some changes which might fix some errors!

**Comment by rjclaasen** [comment]
I unfortunately do not know. I am not using the CR calculations at the moment. Thank you for your work!
